import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { createTestHarness, parseToolResult } from '@chrischall/mcp-utils/test'
import { CreditKarmaClient } from '../src/client.js'
import { registerHealthcheckTools } from '../src/tools/healthcheck.js'
import type { AppContext } from '../src/index.js'

/**
 * A CDN/WAF block is not a rejected credential (chrischall/mcp-host#1015).
 *
 * A refusal page served by the edge in front of Credit Karma answers 403 —
 * the same status as a dead session — before the API ever sees the cookies.
 * These run the REAL client (fetch stubbed) so they fail if anything between
 * the response and the healthcheck drops what the shared classifier reads:
 * the 200-char cut of the GraphQL error body, or the refresh path's fixed
 * "session rejected" copy that replaced any HTML body outright.
 */

// CloudFront's block page, as served (whitespace trimmed, ids made up).
const CLOUDFRONT_BLOCK =
  '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">' +
  '<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">' +
  '<TITLE>ERROR: The request could not be satisfied</TITLE></HEAD><BODY>' +
  '<H1>403 ERROR</H1><H2>The request could not be satisfied.</H2><HR noshade size="1px">' +
  "Request blocked. We can't connect to the server for this app or website at this time. " +
  'There might be too much traffic or a configuration error. Try again later, or contact the app or ' +
  'website owner.<BR clear="all">If you provide content to customers through CloudFront, you can find ' +
  'steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.' +
  '<BR clear="all"><HR noshade size="1px"><PRE>Generated by cloudfront (CloudFront)\n' +
  'Request ID: AbCdEfGhIjKlMnOpQrStUvWxYz0123456789abcdefghijklmnopqr==</PRE><ADDRESS></ADDRESS></BODY></HTML>'

const jwt = (exp: number) =>
  `h.${Buffer.from(JSON.stringify({ exp })).toString('base64url')}.s`
const LIVE = jwt(Math.floor(Date.now() / 1000) + 3600)
const DEAD = jwt(Math.floor(Date.now() / 1000) - 3600)

function blocked(): Response {
  return new Response(CLOUDFRONT_BLOCK, {
    status: 403,
    statusText: 'Forbidden',
    headers: { 'content-type': 'text/html', 'x-cache': 'Error from cloudfront', server: 'CloudFront' },
  })
}

interface Result {
  ok: boolean
  error?: { kind: string; message: string }
  hint: string
}

async function healthcheck(cookies: string): Promise<Result> {
  const ctx = { client: new CreditKarmaClient() } as AppContext
  const h = await createTestHarness((server) =>
    registerHealthcheckTools(server, ctx, { resolve: async () => ({ cookies, source: 'env' }) }),
  )
  const res = await h.client.callTool({ name: 'ck_healthcheck', arguments: {} })
  await h.close?.()
  return parseToolResult<Result>(res as never)
}

describe('a CDN/WAF block reads as edge_blocked, not a rejected credential', () => {
  let fetchMock: ReturnType<typeof vi.fn>

  beforeEach(() => {
    fetchMock = vi.fn()
    vi.stubGlobal('fetch', fetchMock)
  })

  afterEach(() => {
    vi.restoreAllMocks()
    vi.unstubAllGlobals()
  })

  it('on the GraphQL probe itself, with a live session', async () => {
    fetchMock.mockImplementation(async () => blocked())

    const r = await healthcheck(`CKAT=${LIVE}%3B${LIVE}`)

    expect(r.ok).toBe(false)
    expect(r.error?.kind).toBe('edge_blocked')
  })

  it('on the token refresh the probe triggers', async () => {
    // Spent access token, live refresh token: the probe refreshes first, and
    // the edge blocks the refresh POST.
    fetchMock.mockImplementation(async () => blocked())

    const r = await healthcheck(`CKAT=${DEAD}%3B${LIVE}`)

    expect(r.ok).toBe(false)
    expect(r.error?.kind).toBe('edge_blocked')
    expect(r.hint).not.toMatch(/Sign in again/)
  })

  it('control: a JSON 401 from the refresh endpoint is still a rejected session', async () => {
    fetchMock.mockImplementation(
      async () =>
        new Response(JSON.stringify({ error: 'invalid_grant' }), {
          status: 401,
          headers: { 'content-type': 'application/json' },
        }),
    )

    const r = await healthcheck(`CKAT=${DEAD}%3B${LIVE}`)

    expect(r.error?.kind).toBe('credential_rejected')
  })
})
